import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const ppTelegraf = localFont({
  src: [
    {
      path: "../public/font/PPTelegraf-UltraLight.woff2",
      weight: "200",
      style: "normal",
    },
    {
      path: "../public/font/PPTelegraf-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/font/PPTelegraf-Bold.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "../public/font/PPTelegraf-UltraBold.woff2",
      weight: "800",
      style: "normal",
    },
    {
      path: "../public/font/PPTelegraf-Black.woff2",
      weight: "900",
      style: "normal",
    },
  ],
  variable: "--font-pp-telegraf",
});

const ppWoodland = localFont({
  src: [
    {
      path: "../public/font/PPWoodland-Ultralight.woff2",
      weight: "200",
      style: "normal",
    },
    {
      path: "../public/font/PPWoodland-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/font/PPWoodland-Bold.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "../public/font/PPWoodland-Heavy.woff2",
      weight: "900",
      style: "normal",
    },
  ],
  variable: "--font-pp-woodland",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${ppTelegraf.variable} ${ppWoodland.variable} antialiased`}>{children}</body>
    </html>
  );
}
